Repository aio-libs/aiomysql, pull requests merged in 2022-02, with the labels that each got.

#723 Revert "add python 3.11 tests (#722)"
  .github/workflows/ci.yml
  requirements-dev.txt
  tests/conftest.py
Labels: test

#426 Fix pool maxsize unlimited
  CHANGES.txt
  aiomysql/pool.py
  tests/test_pool.py
Labels: bug

#494 Fix async iterator protocol in _SAConnectionContextManager
  CHANGES.txt
  aiomysql/utils.py
  tests/sa/test_sa_connection.py
Labels: bug, sqlalchemy

#727 test against sqlalchemy up to version 1.3.24
  requirements-dev.txt
Labels: test

#626 [doc] Update the create_engine usage example
  docs/sa.rst
Labels: docs, sqlalchemy

#728 Add query timeout tests for #428
  tests/test_cursor.py
  tests/test_sscursor.py
Labels: test, pymysql, pymysql-port

#646 fix SSCursor error raise (#428)
  CHANGES.txt
  aiomysql/connection.py
  tests/test_sscursor.py
Labels: bug

#737 Remove pyroma from tests
  .github/workflows/lint.yml
  Makefile
  requirements-dev.txt
Labels: test
